try {
    undefined; // cause exception
}
catch (err) {
    console.log(err);
}

console.log(err); //ReferenceError